# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/lemonade/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lemonade)

$(call add-radio-file-sha1-checked,radio/abl.img,4875db77f095947337b42d6e48f7a7510f56f4ed)
$(call add-radio-file-sha1-checked,radio/aop.img,a689bcb174585e7e3c233690699a435dd88fdf02)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,7c4101f0ae320392c282b838e7dd1030833aa0ef)
$(call add-radio-file-sha1-checked,radio/cpucp.img,31d1bb6367c24e113ae447aa3f9cf9214fe127d6)
$(call add-radio-file-sha1-checked,radio/devcfg.img,9c2bae9bfb378024220509a9fde0d38614ba9071)
$(call add-radio-file-sha1-checked,radio/dsp.img,cff87289aca6247e74f10cd8856001aea70b784c)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,bce58cc5f0024786726301c7177843abce078739)
$(call add-radio-file-sha1-checked,radio/hyp.img,cc20e96bfe3fcb27f3c1e87dd45f60d25378b4e2)
$(call add-radio-file-sha1-checked,radio/imagefv.img,cab9fcfd3fb926e991dca0bf4a5a9355c0678a35)
$(call add-radio-file-sha1-checked,radio/keymaster.img,4d4dc4c944b0d56f44f54b152369aba3612aea3e)
$(call add-radio-file-sha1-checked,radio/modem.img,1106a89f30c007db4eadff0d73409f85ecb4bf2f)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,c421ed6a194b6a8af94e122de5b571e86b4e88a3)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,70c1fb07ea5d63af49361d57b2a5f5d22a7b5612)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,a8323830dc846e4ba1d4bbcc7e8e6a240c7b5aff)
$(call add-radio-file-sha1-checked,radio/qupfw.img,8aaa9ad57fd52312f29814cdca4a7e3cd8c05b0a)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,e1430333ba7256551d4dc4b3ec614fda94364c4d)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,2708e241c5a0541d01d41167da966cd5a2204e7f)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,c916b482076c289bf1b16c2f529aabf0edd7df4a)
$(call add-radio-file-sha1-checked,radio/xbl.img,134bb102928e3dafce502497325f6e1c15c3c1c1)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,eb604fd317497c379b1a4baf53b3dff8a2937b76)

endif
