# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/lemonade/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lemonade)

$(call add-radio-file,radio/abl.img)
$(call add-radio-file,radio/aop.img)
$(call add-radio-file,radio/bluetooth.img)
$(call add-radio-file,radio/cpucp.img)
$(call add-radio-file,radio/devcfg.img)
$(call add-radio-file,radio/dsp.img)
$(call add-radio-file,radio/engineering_cdt.img)
$(call add-radio-file,radio/featenabler.img)
$(call add-radio-file,radio/hyp.img)
$(call add-radio-file,radio/imagefv.img)
$(call add-radio-file,radio/keymaster.img)
$(call add-radio-file,radio/modem.img)
$(call add-radio-file,radio/multiimgoem.img)
$(call add-radio-file,radio/oplus_sec.img)
$(call add-radio-file,radio/oplusstanvbk.img)
$(call add-radio-file,radio/qupfw.img)
$(call add-radio-file,radio/qweslicstore.img)
$(call add-radio-file,radio/shrm.img)
$(call add-radio-file,radio/splash.img)
$(call add-radio-file,radio/tz.img)
$(call add-radio-file,radio/uefisecapp.img)
$(call add-radio-file,radio/xbl.img)
$(call add-radio-file,radio/xbl_config.img)

endif
