# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/lemonade/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    bluetooth \
    cpucp \
    devcfg \
    dsp \
    engineering_cdt \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    multiimgoem \
    oplus_sec \
    oplusstanvbk \
    qupfw \
    qweslicstore \
    shrm \
    splash \
    tz \
    uefisecapp \
    xbl \
    xbl_config
